common/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    # path('login/', auth_views.LoginView.as_view(
    #     template_name='account/login.html'), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # path('signup/', views.signup, name='signup'),
    # path('password_reset/', views.UserPasswordResetView.as_view(), name="password_reset"),
    # path('password_reset_done/', views.UserPasswordResetDoneView.as_view(), name="password_reset_done"),
    # path('password_reset_confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    # path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    # path('', include('common.urls')),
    path('', include('allauth.urls')),
]

posts/urls.py
from django.urls import path
from .views import base_views, post_views, comment_views

app_name = "posts"

urlpatterns = [
  # base_views.py
  path('', base_views.index, name='index'),
  path('about/', base_views.about, name='about'),

  # post_views.py
  path('list/', post_views.PostListView.as_view(), name='post_list'),
  path('detail/<int:post_id>', post_views.PostDetailView.as_view(), name='post_detail'),
  path('create/', post_views.PostCreateView.as_view(), name='post_create'),
  path('update/<int:post_id>', post_views.PostUpdateView.as_view(), name='post_update'),
  path('delete/<int:post_id>', post_views.PostDeleteView.as_view(), name='post_delete'),
  path('like/<int:post_id>', post_views.post_like, name='post_like'),

  # comment_views.py
  path('comment/create/<int:post_id>', comment_views.comment_create, name='comment_create'),
  path('comment/update/<int:comment_id>', comment_views.comment_update, name='comment_update'),
  path('comment/delete/<int:comment_id>', comment_views.comment_delete, name='comment_delete'),
  path('comment/like/<int:comment_id>', comment_views.comment_like, name='comment_like'),
]

common/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

posts/models.py
from django.db import models
from common.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100, verbose_name="제목")
    content = models.TextField(verbose_name="내용")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    dt_created = models.DateTimeField(auto_now_add=True)
    dt_updated = models.DateTimeField(null=True, blank=True)
    like = models.ManyToManyField(User, blank=True, related_name='post_like')
    bookmark = models.ManyToManyField(User, blank=True, related_name='post_bookmark')

    def __str__(self):
        return self.title


class Comment(models.Model):
    content = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comment_author')
    dt_created = models.DateTimeField(auto_now_add=True)
    dt_updated = models.DateTimeField(null=True, blank=True)
    like = models.ManyToManyField(User, blank=True, related_name='comment_like')

    def __str__(self):
        return self.content

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label='이메일')

    class Meta:
        model = User
        fields =('username', 'email')

posts/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
      model = Post
      exclude = ('author', 'dt_updated', 'like', 'bookmark',)


class CommentForm(forms.ModelForm):
    class Meta:
      model = Comment
      fields = ['content']

common/views.py
# Create your views here.

posts/views/base_views.py
from django.shortcuts import render

def index(request):
    return render(request, 'posts/index.html')


def about(request):
    return render(request, 'about.html')

posts/views/comment_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.utils import timezone
from django.contrib import messages
from posts.models import Post, Comment
from posts.forms import CommentForm

# Create your views here.

@login_required(login_url='account_login')
def comment_create(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('posts:post_detail', post_id)

    messages.error(request, '내용이 없는 댓글은 등록할 수 없습니다.')
    return redirect('posts:post_detail', post_id)
    

@login_required(login_url='account_login')
def comment_update(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.dt_updated = timezone.now()
            comment.save()
            return redirect('posts:post_detail', post_id=comment.post.id)
    else:
        form = CommentForm(instance=comment)
    ctx = {'form' : form, 'comment' : comment}
    return render(request, 'posts/comment_update.html', ctx)


@login_required(login_url='account_login')
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if comment.author == request.user:
        comment.delete()
    return redirect('posts:post_detail', post_id=comment.post.id)


@login_required(login_url='account_login')
def comment_like(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    
    if comment.like.filter(id=request.user.id).exists():
        comment.like.remove(request.user)
    else:
        comment.like.add(request.user)
    return redirect('posts:post_detail', post_id=comment.post.id)

posts/views/post_views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator
from django.utils import timezone
from django.urls import reverse
from django.contrib import messages
from posts.models import Post
from posts.forms import PostForm


class PostListView(ListView):
    model = Post
    ordering = '-dt_created'
    paginate_by = 10


class PostDetailView(DetailView):
    model = Post
    pk_url_kwarg = 'post_id'


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('posts:post_detail', kwargs={'post_id' : self.object.id})


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = "posts/post_update.html"
    pk_url_kwarg = 'post_id'

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.dt_updated = timezone.now()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('posts:post_detail', kwargs={'post_id' : self.object.id})


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    pk_url_kwarg = 'post_id'

    def get_success_url(self):
        return reverse('posts:post_list')


@login_required(login_url='account_login')
def post_like(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    
    if post.like.filter(id=request.user.id).exists():
        post.like.remove(request.user)
    else:
        post.like.add(request.user)
    return redirect('posts:post_detail', post_id)

templates/about.html
{% extends 'base.html' %}
{% block content %}
about page
{% endblock %}

templates/base.html
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<!Doctype html>
<html lang='ko'>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- reference your installed Font Awesome Free package's files here -->
    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
    <!-- reference your installed Font Awesome Free package's files here -->
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <!-- Our project just needs Font Awesome Free's Solid + Brand files -->
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <title>SSUWMC</title>
</head>
<body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
    {% include 'footer.html' %}
    {% block script %}
    {% endblock %}
</body>
</html>

templates/footer.html
<div class="wrapper">
    <footer class="footer bg-light fixed-bottom" style="user-select: auto;">
        <div class="container mt-3" style="user-select: auto;">
            <span class="text-muted" style="user-select: auto;">©2022 • SSUWMC.COM</span>
            <span class="float-end small" style="user-select: auto;">
                <a href="https://oshmos.github.io" style="user-select: auto; text-decoration: none;">
                    MADE BY OSHMOS
                </a>
            </span>
        </div>
      </footer>
</div>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{field.label}}</strong>
                {{error}}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{error}}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="user-select: auto;">
  <div class="container d-flex" style="user-select: auto;">
      <div class="d-flex">
          <a class="navbar-brand" href="{% url 'posts:index' %}" style="user-select: auto;">Westminster Choir</a>
          <a href="{% url 'posts:about' %}" class="nav-link text-dark" style="user-select: auto;">About</a>
          <a href="{% url 'posts:post_list' %}" class="nav-link text-dark" style="user-select: auto;">게시판</a>
      </div>

      <button class="btn btn-light d-inline-block d-lg-none ml-auto collapsed"
              type="button" style="user-select: auto;"
              data-bs-toggle="collapse" data-bs-target="#navbarNav"
              aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <i class="fas fa-bars"></i>
      </button>
      <div class="navbar-collapse collapse justify-content-end" id="navbarNav" style="user-select: auto;">
          <ul class="nav navbar-nav ml-auto" style="user-select: auto;">
              {% if user.is_authenticated %}
                  <li class="nav-item">
                      <span class="nav-link">안녕하세요. {{ user }}님!</span>
                  </li>
                  <li class="nav-item">
                      <a href="{% url 'account_logout' %}" class="nav-link">로그아웃</a>
                  </li>
                  {% else %}
                  <li class="nav-item " style="user-select: auto;">
                      <a class="nav-link" href="{% url 'account_login' %}" style="user-select: auto;"><i class="fas fa-sign-in-alt" style="user-select: auto;"></i> 로그인</a>
                  </li>
                  <li class="nav-item " style="user-select: auto;">
                      <a class="nav-link" href="{% url 'account_signup' %}" style="user-select: auto;"><i class="fas fa-user-plus" style="user-select: auto;"></i> 회원가입</a>
                  </li>  
              {% endif %}
          </ul>
      </div>
  </div>
</nav>

templates/posts/comment_update.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <form class="post-form" method="POST">
        {% csrf_token %}
        {% include 'form_errors.html' %}
        <div class="form-group">
            <textarea class='form-control' name="content" id="content"
                      autofocus
                      rows="10">{{form.content.value|default_if_none:''}}</textarea>
        </div>
        <hr>
        <button type="submit" class="btn btn-primary">수정하기</button>
    </form>
</div>
{% endblock %}

templates/posts/form.html
<div class="container mt-3" style="user-select: auto;">
  <div class="row" style="user-select: auto;">
      <div class="col-sm-12 col-md-3 col-lg-3 p-2" style="user-select: auto;"></div>
      <div class="col-sm-12 col-md-6 col-lg-6 p-2" style="user-select: auto;">
          <div id="content" class="border-top" style="user-select: auto;">
              <div class="content_block" style="user-select: auto;">
                  {% block form %}
                  {% endblock %}
              </div>
          </div>
      </div>
      <div class="col-sm-12 col-md-3 col-lg-3 p-2" style="user-select: auto;"></div>
  </div>
</div>

templates/posts/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-lg my-3">
  <div id="myCarousel" class="carousel carousel-dark slide" data-bs-ride="carousel">
      <!-- Carousel indicators -->
      <ol class="carousel-indicators">
          <li data-bs-target="#myCarousel" data-bs-slide-to="0" class="active"></li>
          <li data-bs-target="#myCarousel" data-bs-slide-to="1"></li>
          <li data-bs-target="#myCarousel" data-bs-slide-to="2"></li>
      </ol>
      
      <!-- Wrapper for carousel items -->
      <div class="carousel-inner">
          <div class="carousel-item active">
              <img src="{% static 'img/img0.jpg' %}" class="d-block w-100" alt="Slide 0">
              <div class="carousel-caption d-none d-md-block">
                  <h5>First slide label</h5>
                  <p>Some demonstrative placeholder content for the first slide.</p>
              </div>
          </div>
          <div class="carousel-item">
              <img src="{% static 'img/img1.jpg' %}" class="d-block w-100" alt="Slide 1">
              <div class="carousel-caption d-none d-md-block">
                  <h5>Second slide label</h5>
                  <p>Some demonstrative placeholder content for the second slide.</p>
              </div>
          </div>
          <div class="carousel-item">
              <img src="{% static 'img/img2.jpg' %}" class="d-block w-100" alt="Slide 2">
              <div class="carousel-caption d-none d-md-block">
                  <h5>Third slide label</h5>
                  <p>Some demonstrative placeholder content for the third slide.</p>
              </div>
          </div>
      </div>

      <!-- Carousel controls -->
      <a class="carousel-control-prev" href="#myCarousel" data-bs-slide="prev">
          <span class="carousel-control-prev-icon"></span>
      </a>
      <a class="carousel-control-next" href="#myCarousel" data-bs-slide="next">
          <span class="carousel-control-next-icon"></span>
      </a>
  </div>
</div>
{% endblock %}

templates/posts/post_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-3">
  <div class="row">
    <div class="col-sm-12 col-md-3 col-lg-3 p-2"></div>
    <div class="col-sm-12 col-md-6 col-lg-6 p-2">
      <div id="content" class="border-top" style="user-select: auto;">
        <div class="content_block" style="user-select: auto;">
          <h4 class="text-center" style="user-select: auto;">이 글을 정말 지우시겠어요?</h4>
          <div class="card mt-3">
            <div class="card-body">
              <form method='post'>
                {% csrf_token %}
                <div class="row">
                  <div class="col-3 col-sm-3 col-md-3 col-lg-3"></div>
                  <input class="btn btn-primary col-2 col-sm-2 col-md-2 col-lg-2" type="submit" value="삭제">
                  <div class="col-2 col-sm-2 col-md-2 col-lg-2"></div>
                  <a href="{% url 'posts:post_detail' post.id %}" class="btn btn-outline-dark col-2 col-sm-2 col-md-2 col-lg-2">취소</a>
                  <div class="col-3 col-sm-3 col-md-3 col-lg-3"></div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-12 col-md-3 col-lg-3 p-2"></div>
  </div>
</div>
{% endblock %}

templates/posts/post_detail.html
{% extends 'base.html' %}
{% block content %}
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-dismissible alert-danger text-center">
            <strong>{{message}}</strong>
            <a href={% url 'posts:post_detail' post.id %} class="btn-close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true"></span>
            </a>
        </div>
    {% endfor %}
{% endif %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-sm-12 col-lg-2 col-md-1"></div>
        <div class="col-sm-12 col-lg-8 col-md-10">
            <div class="card">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">
                        <h3>{{ post.title }}</h3>
                        
                        <p>{{ post.content }}</p>
                    </div>
                    <div class="d-flex justify-content-end">
                        {% if post.dt_updated %}
                            <div class="badge bg-light p-2 text-dark text-start mx-3">
                                <div class="mb-2">{{ post.author }}</div>
                                <div>{{ post.dt_updated }}(수정됨)</div>
                            </div>
                        {% else %}
                            <div class="badge bg-light p-2 text-dark text-start">
                                <div class="mb-2">{{ post.author }}</div>
                                <div>{{ post.dt_created }}</div>
                            </div>
                        {% endif %}
                    </div>
                    <div class="d-flex justify-content-between">
                        <span>
                            {% if post.author == request.user %}
                                <a href="{% url 'posts:post_list' %}"
                                    class="btn btn-sm btn-outline-secondary">목록</a>
                                <a href="{% url 'posts:post_update' post.id %}"
                                    class="btn btn-sm btn-outline-secondary">수정</a>
                                <a href="{% url 'posts:post_delete' post.id %}"
                                    class="delete btn btn-sm btn-outline-secondary">삭제</a>
                            {% else %}
                                <a href="{% url 'posts:post_list' %}"
                                    class="btn btn-sm btn-outline-secondary">목록</a>
                            {% endif %}
                        </span>
                        <span class="pt-1">
                            <a href={% url 'posts:post_like' post.id %} class="text-decoration-none">
                                <span style="color: red;" class="">
                                    {% if user in post.like.all %}
                                        <i class="fas fa-heart"></i>
                                    {% else %}
                                        <i class="far fa-heart"></i>
                                    {% endif %}
                                </span>
                                <span class="text-dark">
                                    {{ post.like.count }}
                                </span>
                            </a>
                        </span>
                    </div>
                </div>
            </div>
            {% if post.comment_set.count > 0 %}
            <div class="card">
                <div class="card-body">
                    <div class="card-text">
                        <div class="mt-3">
                            {% for comment in post.comment_set.all %}
                                <div class="card-text" style="white-space: pre-line;">
                                    <p>{{ comment.content }}</p>
                                </div>
                                <div class="d-flex justify-content-end">
                                    {% if comment.dt_updated %}
                                        <div class="badge bg-light p-2 text-dark text-start mx-3">
                                            <div class="mb-2">{{ comment.author }}</div>
                                            <div>{{ comment.dt_updated }}(수정됨)</div>
                                        </div>
                                    {% else %}
                                        <div class="badge bg-light p-2 text-dark text-start">
                                            <div class="mb-2">{{ comment.author }}</div>
                                            <div>{{ comment.dt_created }}</div>
                                        </div>
                                    {% endif %}
                                </div>
                                <div class="d-flex justify-content-between">
                                    <span>
                                        {% if comment.author == request.user %}
                                            <a href="{% url 'posts:comment_update' comment.id %}"
                                                class="btn btn-sm btn-outline-secondary">수정</a>
                                            <a href="{% url 'posts:comment_delete' comment.id %}"
                                                class="delete btn btn-sm btn-outline-secondary">삭제</a>
                                        {% endif %}
                                    </span>
                                    <span class="pt-1">
                                        <a href={% url 'posts:comment_like' comment.id %} class="text-decoration-none">
                                            <span style="color: red;" class="">
                                                {% if user in comment.like.all %}
                                                    <i class="fas fa-heart"></i>
                                                {% else %}
                                                    <i class="far fa-heart"></i>
                                                {% endif %}
                                            </span>
                                            <span class="text-dark">
                                                {{ comment.like.count }}
                                            </span>
                                        </a>
                                    </span>
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                    <hr>
                    <form action="{% url 'posts:comment_create' post.id %}" method="POST" class="my-3">
                        {% csrf_token %}
                        {% include 'form_errors.html' %}
                        <label for="content"></label>
                        <textarea name="content" id="content"
                                {% if post.comment_set.count < 2 %}autofocus{% endif %}
                                {% if not user.is_authenticated %}disabled{% endif %}
                                class="form-control" rows="10" ></textarea>
                        <hr>
                        <input type="submit" value="등록하기" class="btn btn-primary">
                    </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-lg-2 col-md-1"></div>
    </div>
</div>
{% endblock %}

templates/posts/post_form.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
<div class="container">
    <div class="row" style="user-select: auto;">
        <div class="col-sm-12 col-md-3 col-lg-3 p-2" style="user-select: auto;"></div>
        <div class="col-sm-12 col-md-6 col-lg-6 p-2" style="user-select: auto;">
            <div id="content" class="border-top" style="user-select: auto;">
                <div class="content_block" style="user-select: auto;">
                    <h5 class="my-3 border-bottom pb-2">게시글 등록</h5>
                    <form method="post" class="post-form my-3">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        {% buttons %}
                        <button type="submit" class="btn btn-primary">등록하기</button>
                        {% endbuttons %}
                    </form>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-3 col-lg-3 p-2" style="user-select: auto;"></div>
    </div>
</div>
{% endblock %}

templates/posts/post_list.html
{% extends 'base.html' %}
{% load posts_filter %}
{% block content %}
  <div class="container my-3">
    <table class="table">
        <thead>
        <tr class="text-center thead-dark">
            <th>공감</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if page_obj.object_list %}
        {% for post in page_obj.object_list %}
        <tr class="text-center">
            <td>
                {% if post.like.all.count > 0 %}
                <span class="badge bg-warning px-2 py-1 text-dark">
                    {{ post.like.all.count }}
                </span>
                {% else %}
                <span class="badge bg-light px-2 py-1" style="color: rgb(204, 204, 204);">
                    {{ post.like.all.count }}
                </span>
                {% endif %}
            </td>
            <td class="text-left">
                <a href="{% url 'posts:post_detail' post.id %}">
                    {{ post.title }}
                </a>
            </td>
            <td>{{ post.author }}</td>
            {% if post.dt_updated %}
                <td>{{ post.dt_updated }}</td>
            {% else %}
                <td>{{ post.dt_created }}</td>
            {% endif %}
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">글이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <ul class="pagination justify-content-center">
        {% if post_list.has_previous %}
        <li class="page-item">
            <a href="?page={{page_obj.previous_page_number}}"
              class="page-link">
                &lt;
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a href="#" class="page-link" tabindex="-1" aria-disabled="true">
                &lt;
            </a>
        </li>
        {% endif %}
        {% for page_number in page_obj.paginator.page_range %}
        {% if page_number >= page_obj.number|add:-5 and page_number <= page_obj.number|add:5 %}
            {% if page_number == page_obj.number %}
            <li class="page-item active" aria-current="page">
                <a href="?page={{page_number}}" class="page-link">
                    {{page_number}}
                </a>
            </li>
            {% else %}
            <li class="page-item">
                <a href="?page={{page_number}}" class="page-link">
                    {{page_number}}
                </a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item">
            <a href="?page={{page_obj.next_page_number}}"
              class="page-link">
                &gt;
            </a>
        </li>
        {% endif %}
    </ul>
    <a href="{% url 'posts:post_create' %}" class="btn btn-primary">
        작성하기
    </a>
  </div>
{% endblock %}

templates/posts/post_update.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
<div class="container mt-3">
    <div class="row" style="user-select: auto;">
        <div class="col-sm-12 col-md-3 col-lg-3 p-2" style="user-select: auto;"></div>
        <div class="col-sm-12 col-md-6 col-lg-6 p-2" style="user-select: auto;">
            <div id="content" class="border-top" style="user-select: auto;">
                <div class="content_block" style="user-select: auto;">
                    <h5 class="my-3 border-bottom pb-2">게시글 수정</h5>
                    <form method="post" class="post-form my-3">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        {% buttons %}
                            <button type="submit" class="btn btn-primary">수정하기</button>
                        {% endbuttons %}
                    </form>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-3 col-lg-3 p-2" style="user-select: auto;"></div>
    </div>
</div>
{% endblock %}